package installer

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// Every test here drives the exported operation (Install / Uninstall), not
// the helper under repair. The 2026-09-07 audit could only exercise extracted
// helpers, so proving the composed flow reaches these branches is part of the
// fix, not an assumption behind it.

// F01: creating AGENTS.md does not confer ownership of every byte written
// into it later. Uninstall must strip the block and keep the prose.
func TestUninstall_AgentsCreatedByInstall_ConsumerProsePreserved(t *testing.T) {
	root := tempRepo(t, true)
	mustInstall(t, root)

	prose := "\n## Deployment\n\nAll deploys require a second approver.\n"
	before := rf(t, root, agentsTarget)
	pf(t, root, agentsTarget, before+prose)

	var sb strings.Builder
	if err := Uninstall(root, &sb); err != nil {
		t.Fatalf("uninstall: %v", err)
	}

	got, err := os.ReadFile(filepath.Join(root, agentsTarget))
	if err != nil {
		t.Fatalf("consumer prose lost: AGENTS.md was deleted (%v)\n%s", err, sb.String())
	}
	if !strings.Contains(string(got), "second approver") {
		t.Errorf("consumer prose missing after uninstall:\n%s", got)
	}
	if strings.Contains(string(got), blockBegin) || strings.Contains(string(got), blockEnd) {
		t.Errorf("managed block survived uninstall:\n%s", got)
	}
}

// Control for F01: with nothing but the generated header outside the block,
// the file installed by zharness is still removed.
func TestUninstall_AgentsCreatedByInstall_BoilerplateOnlyIsRemoved(t *testing.T) {
	root := tempRepo(t, true)
	mustInstall(t, root)

	var sb strings.Builder
	if err := Uninstall(root, &sb); err != nil {
		t.Fatalf("uninstall: %v", err)
	}
	if _, err := os.Stat(filepath.Join(root, agentsTarget)); !os.IsNotExist(err) {
		t.Errorf("AGENTS.md held only generated boilerplate; uninstall must remove it\n%s", sb.String())
	}
}

// F06: a second install must not record the bytes the first install
// generated as that file's pre-install original.
func TestInstall_Twice_DoesNotCaptureGeneratedBytesAsOriginal(t *testing.T) {
	root := tempRepo(t, true)
	withSource(t, map[string]string{"WORKFLOW.md": wfUp1})
	mustInstall(t, root)
	mustInstall(t, root)

	if p, ok := findOriginal(root, workflowTarget); ok {
		b, _ := os.ReadFile(p)
		t.Fatalf("second install captured generated bytes as a pre-install original at %s:\n%s", p, b)
	}
	if got := loadOwnership(root).get(kindFile, workflowTarget); got != originCreated {
		t.Errorf("ownership of %s = %q, want %q", workflowTarget, got, originCreated)
	}

	var sb strings.Builder
	if err := Uninstall(root, &sb); err != nil {
		t.Fatalf("uninstall: %v", err)
	}
	if _, err := os.Stat(filepath.Join(root, workflowTarget)); !os.IsNotExist(err) {
		t.Errorf("install/reinstall/uninstall left %s behind\n%s", workflowTarget, sb.String())
	}
}

// F06 control: a genuinely pre-existing file is still captured and restored.
func TestInstall_Twice_PreexistingFileStillRestored(t *testing.T) {
	root := tempRepo(t, true)
	withSource(t, map[string]string{"WORKFLOW.md": wfUp1})
	mine := "# my workflow, written before zharness\n"
	pf(t, root, workflowTarget, mine)

	mustInstall(t, root)
	mustInstall(t, root)

	var sb strings.Builder
	if err := Uninstall(root, &sb); err != nil {
		t.Fatalf("uninstall: %v", err)
	}
	if got := rf(t, root, workflowTarget); got != mine {
		t.Errorf("pre-install original not restored:\ngot  %q\nwant %q\n%s", got, mine, sb.String())
	}
}

// F07: uninstall removes the ignore lines it appended and leaves an
// identical rule the consumer already had.
func TestUninstall_PreexistingGitignoreRule_Survives(t *testing.T) {
	root := tempRepo(t, true)
	pf(t, root, gitignoreTarget, "keep/\n/"+zharnessDir+"/\n")
	mustInstall(t, root)

	if got := loadOwnership(root).get(kindGitignore, "/"+zharnessDir+"/"); got != originPreexisting {
		t.Fatalf("consumer ignore rule recorded as %q, want %q", got, originPreexisting)
	}

	var sb strings.Builder
	if err := Uninstall(root, &sb); err != nil {
		t.Fatalf("uninstall: %v", err)
	}
	got := rf(t, root, gitignoreTarget)
	if !containsLine(got, "/"+zharnessDir+"/") {
		t.Errorf("consumer-owned ignore rule removed by uninstall:\n%s", got)
	}
	if !containsLine(got, "keep/") {
		t.Errorf("unrelated ignore rule removed by uninstall:\n%s", got)
	}
	if containsLine(got, gitignoreMarker) {
		t.Errorf("installer-added marker survived uninstall:\n%s", got)
	}
}

// F07 control: a rule only the installer added is still cleaned up.
func TestUninstall_InstallerAddedGitignoreRule_IsRemoved(t *testing.T) {
	root := tempRepo(t, true)
	pf(t, root, gitignoreTarget, "keep/\n")
	mustInstall(t, root)

	var sb strings.Builder
	if err := Uninstall(root, &sb); err != nil {
		t.Fatalf("uninstall: %v", err)
	}
	got := rf(t, root, gitignoreTarget)
	if containsLine(got, "/"+zharnessDir+"/") {
		t.Errorf("installer-added ignore rule survived uninstall:\n%s", got)
	}
	if !containsLine(got, "keep/") {
		t.Errorf("unrelated ignore rule removed by uninstall:\n%s", got)
	}
}

// R5: an installation made before the ledger existed is seeded from the
// .orig and manifest evidence the pre-ledger code already relied on, so its
// uninstall behaves exactly as it did before.
func TestUninstall_LegacyInstall_SeedsFromSurvivingEvidence(t *testing.T) {
	root := tempRepo(t, true)
	withSource(t, map[string]string{"WORKFLOW.md": wfUp1})
	mine := "# predates zharness\n"
	pf(t, root, workflowTarget, mine)
	pf(t, root, gitignoreTarget, "/"+zharnessDir+"/\n")
	mustInstall(t, root)

	// simulate a pre-0008 installation: manifest and originals intact,
	// no ledger on disk
	if err := os.Remove(filepath.Join(root, ownershipFile)); err != nil {
		t.Fatal(err)
	}

	var sb strings.Builder
	if err := Uninstall(root, &sb); err != nil {
		t.Fatalf("uninstall: %v", err)
	}
	if got := rf(t, root, workflowTarget); got != mine {
		t.Errorf("seeded legacy install lost the pre-install original:\ngot %q\n%s", got, sb.String())
	}
	if got := rf(t, root, gitignoreTarget); !containsLine(got, "/"+zharnessDir+"/") {
		t.Errorf("seeded legacy install removed a consumer ignore rule:\n%s", got)
	}
}

// R3: with no ledger and no manifest there is nothing left to seed from.
// Unknown provenance is kept, never resolved by deleting.
func TestUninstall_UnknownProvenance_KeepsManagedFile(t *testing.T) {
	root := tempRepo(t, true)
	withSource(t, map[string]string{"WORKFLOW.md": wfUp1})
	mustInstall(t, root)

	// .zharness/base lost entirely: no ledger, no manifest, no originals
	if err := os.RemoveAll(filepath.Join(root, baseDir)); err != nil {
		t.Fatal(err)
	}

	var sb strings.Builder
	if err := Uninstall(root, &sb); err != nil {
		t.Fatalf("uninstall: %v", err)
	}
	if _, err := os.Stat(filepath.Join(root, workflowTarget)); err != nil {
		t.Errorf("managed file with unknown provenance was deleted: %v\n%s", err, sb.String())
	}
	if !strings.Contains(sb.String(), "no recorded base; provenance unknown") {
		t.Errorf("uninstall did not name why the file was kept:\n%s", sb.String())
	}
}

// R6: the summary reports what happened instead of asserting a blanket
// guarantee the run did not enforce.
func TestUninstall_Summary_ReportsKeptFilesInsteadOfBlanketClaim(t *testing.T) {
	root := tempRepo(t, true)
	withSource(t, map[string]string{"WORKFLOW.md": wfUp1})
	mustInstall(t, root)
	pf(t, root, workflowTarget, "locally rewritten\n")

	var sb strings.Builder
	if err := Uninstall(root, &sb); err != nil {
		t.Fatalf("uninstall: %v", err)
	}
	out := sb.String()
	if strings.Contains(out, "consumer-owned files were never touched") {
		t.Errorf("uninstall still prints an unconditional preservation guarantee:\n%s", out)
	}
	if !strings.Contains(out, "kept:") || !strings.Contains(out, workflowTarget) {
		t.Errorf("uninstall summary does not name the kept file:\n%s", out)
	}
}

// Found by the 2026-09-08 full check. The ledger used to be saved only after
// the write loop, so an install that failed midway left managed files on disk
// with no record of who made them. Blocking the first target's directory makes
// Install fail for real; the ledger must already be on disk when it does.
func TestInstall_FailsMidway_LedgerIsAlreadyOnDisk(t *testing.T) {
	root := tempRepo(t, true)
	withSource(t, map[string]string{"WORKFLOW.md": wfUp1})
	// `docs` as a regular file makes MkdirAll for docs/WORKFLOW.md fail.
	if err := os.WriteFile(filepath.Join(root, "docs"), []byte("not a directory\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	var sb strings.Builder
	if err := Install(root, "t", &sb); err == nil {
		t.Fatalf("install reported success with docs/ blocked\n%s", sb.String())
	}
	own := loadOwnership(root)
	if got := own.get(kindFile, workflowTarget); got != originCreated {
		t.Fatalf("a failed install left %s recorded as %q; the ledger must be written before the first managed file", workflowTarget, got)
	}
}

// The state a genuinely interrupted install leaves: the ledger is on disk
// (it is written first) but the base manifest and originals are not (they are
// written last). The retry must read the record rather than re-deriving
// provenance from the files the first attempt already wrote.
func TestInstall_InterruptedThenRetried_DoesNotRelabelGeneratedFiles(t *testing.T) {
	root := tempRepo(t, true)
	withSource(t, map[string]string{"WORKFLOW.md": wfUp1})
	mustInstall(t, root)

	if err := os.Remove(filepath.Join(root, manifestFile)); err != nil {
		t.Fatal(err)
	}
	if err := os.RemoveAll(filepath.Join(root, originalDir)); err != nil {
		t.Fatal(err)
	}

	mustInstall(t, root)

	if p, ok := findOriginal(root, workflowTarget); ok {
		b, _ := os.ReadFile(p)
		t.Fatalf("retry after an interrupted install captured generated bytes as a pre-install original at %s:\n%s", p, b)
	}
	if got := loadOwnership(root).get(kindFile, workflowTarget); got != originCreated {
		t.Fatalf("retry recorded %s as %q, want %q", workflowTarget, got, originCreated)
	}

	var sb strings.Builder
	if err := Uninstall(root, &sb); err != nil {
		t.Fatalf("uninstall: %v", err)
	}
	if _, err := os.Stat(filepath.Join(root, workflowTarget)); !os.IsNotExist(err) {
		t.Errorf("uninstall left a file zharness created behind\n%s", sb.String())
	}
}

// The ledger is append-only per key: the first decision is the durable one.
func TestOwnership_RecordIsWriteOnce(t *testing.T) {
	o := newOwnership()
	if got := o.record(kindFile, "a.md", originPreexisting); got != originPreexisting {
		t.Fatalf("first record returned %q", got)
	}
	if got := o.record(kindFile, "a.md", originCreated); got != originPreexisting {
		t.Errorf("a later install relabelled a recorded origin: got %q", got)
	}
	if got := o.get(kindFile, "never-seen.md"); got != originUnknown {
		t.Errorf("unseen key = %q, want %q", got, originUnknown)
	}
}

// Sibling of the interrupted-install defect, found by the second 2026-09-08
// full check. decideAll persists the *file* rows before the first write, but
// the per-line .gitignore rows are only recorded inside appendGitignoreEntries
// and reach disk in the final save, after saveBase. An install interrupted in
// that window leaves the ignore lines on disk with no row naming them ours,
// and the retry reads them back as the consumer's (F07 again).
func TestInstall_FailsMidway_LedgerAlreadyOwnsItsIgnoreLines(t *testing.T) {
	root := tempRepo(t, true)
	withSource(t, map[string]string{"WORKFLOW.md": wfUp1})
	if err := os.WriteFile(filepath.Join(root, "docs"), []byte("not a directory\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	var sb strings.Builder
	if err := Install(root, "t", &sb); err == nil {
		t.Fatalf("install reported success with docs/ blocked\n%s", sb.String())
	}
	own := loadOwnership(root)
	for _, want := range gitignoreWants {
		if got := own.get(kindGitignore, want); got != originCreated {
			t.Fatalf("a failed install recorded ignore line %q as %q; provenance must be on disk before .gitignore is written", want, got)
		}
	}
}
