package installer

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Ownership is the durable record of who created each managed byte
// (ADR 0008). Presence on disk is a fact about now; provenance is a fact
// about the past, and the past is only knowable if it was written down at
// the time. An origin is therefore fixed on the first decision for a key
// and never revised — a second install cannot relabel bytes the first one
// generated, and uninstall never infers ownership from a stat call.
const ownershipFile = ".zharness/base/ownership.tsv"

const (
	originCreated     = "created_by_installer"
	originPreexisting = "preexisting"
	originUnknown     = "unknown"
)

const (
	kindFile      = "file"
	kindGitignore = "gitignore"
)

// agentsCreatedHeader is the only prose the installer itself writes outside
// the marked block when it creates AGENTS.md. Anything else outside the
// block is the consumer's (F01).
const agentsCreatedHeader = "# Agents"

type ownership struct {
	order  []string // "kind\tkey", stable output order
	origin map[string]string
}

func ownKey(kind, key string) string { return kind + "\t" + key }

func newOwnership() *ownership { return &ownership{origin: map[string]string{}} }

func loadOwnership(root string) *ownership {
	o := newOwnership()
	raw, err := os.ReadFile(filepath.Join(root, ownershipFile))
	if err != nil {
		return o
	}
	for _, ln := range strings.Split(strings.TrimRight(string(raw), "\n"), "\n") {
		parts := strings.Split(ln, "\t")
		if len(parts) != 3 {
			continue
		}
		o.set(parts[0], parts[1], parts[2])
	}
	return o
}

func (o *ownership) set(kind, key, origin string) {
	k := ownKey(kind, key)
	if _, ok := o.origin[k]; !ok {
		o.order = append(o.order, k)
	}
	o.origin[k] = origin
}

func (o *ownership) has(kind, key string) bool {
	_, ok := o.origin[ownKey(kind, key)]
	return ok
}

// record fixes an origin the first time a key is seen and returns whatever
// is already recorded on every later call.
func (o *ownership) record(kind, key, origin string) string {
	if cur, ok := o.origin[ownKey(kind, key)]; ok {
		return cur
	}
	o.set(kind, key, origin)
	return origin
}

func (o *ownership) get(kind, key string) string {
	if v, ok := o.origin[ownKey(kind, key)]; ok {
		return v
	}
	return originUnknown
}

func (o *ownership) save(root string) error {
	var b strings.Builder
	for _, k := range o.order {
		parts := strings.SplitN(k, "\t", 2)
		if len(parts) != 2 {
			continue
		}
		fmt.Fprintf(&b, "%s\t%s\t%s\n", parts[0], parts[1], o.origin[k])
	}
	return writeFileAtomic(filepath.Join(root, ownershipFile), []byte(b.String()))
}

// decideFileOrigin records, once, whether dst predates zharness. Existence
// on disk decides only the first time; afterwards the ledger answers, which
// is what stops a reinstall from capturing generated bytes as a pre-install
// original (F06).
func decideFileOrigin(root string, o *ownership, dst string) string {
	live := originCreated
	if _, err := os.Stat(filepath.Join(root, dst)); err == nil {
		live = originPreexisting
	}
	return o.record(kindFile, dst, live)
}

// decideAll fixes the origin of every managed path before the installer
// writes its first byte. Without this the ledger is only saved after the
// write loop, so an install that fails midway leaves generated files on disk
// with their provenance still unwritten — and the retry, finding no ledger
// and no manifest to seed from, reads those files as pre-existing and
// captures the generated bytes as their own original (F06 again, found by
// the 2026-09-08 full check).
func (o *ownership) decideAll(root string, targets []Target) {
	for _, t := range targets {
		decideFileOrigin(root, o, t.Dst)
	}
	decideFileOrigin(root, o, agentsTarget)
	decideFileOrigin(root, o, gitignoreTarget)
	// An ignore line's provenance has to be fixed here for the same reason a
	// file's does. Deciding it inside the writer left the lines on disk ahead
	// of the row naming them ours, so an install interrupted in that window
	// came back and read its own lines as the consumer's (F07 again, found by
	// the second 2026-09-08 full check).
	existing := ""
	if b, err := os.ReadFile(filepath.Join(root, gitignoreTarget)); err == nil {
		existing = string(b)
	}
	for _, want := range gitignoreWants {
		if containsLine(existing, want) {
			o.record(kindGitignore, want, originPreexisting)
		} else {
			o.record(kindGitignore, want, originCreated)
		}
	}
}

// captureIfPreexisting captures a pristine copy only for a path the ledger
// attributes to the consumer.
func captureIfPreexisting(root string, o *ownership, dst string) error {
	if decideFileOrigin(root, o, dst) != originPreexisting {
		return nil
	}
	return captureOriginal(root, dst)
}

// seedLegacy reconstructs the ledger for an installation made before it
// existed. It uses only the evidence the pre-ledger code itself relied on,
// so a legacy consumer's uninstall behaves as it does today wherever that
// evidence survives, and degrades to keep-and-warn only where it does not.
//
// base carries the recorded upstream bytes per managed path: an .orig whose
// content is exactly those bytes is the F06 artifact — a generated file
// recorded as its own predecessor — not a real pre-install original.
func (o *ownership) seedLegacy(root string, targets []Target, base map[string][]byte) {
	for _, t := range targets {
		o.seedPath(root, t.Dst, base[t.Dst])
	}
	o.seedPath(root, agentsTarget, nil)
	o.seedGitignore(root)
}

func (o *ownership) seedPath(root, dst string, upstream []byte) {
	if o.has(kindFile, dst) {
		return
	}
	if _, err := os.Stat(filepath.Join(root, dst)); err != nil {
		return // not on disk: let the next install decide live
	}
	orig, hasOrig := readOriginal(root, dst)
	switch {
	case !hasOrig:
		o.set(kindFile, dst, originCreated)
	case upstream != nil && bytesEqual(orig, upstream):
		o.set(kindFile, dst, originCreated)
	default:
		o.set(kindFile, dst, originPreexisting)
	}
}

// seedGitignore is exact rather than heuristic: install captured .gitignore's
// pristine bytes if and only if the file existed beforehand, so a managed
// line present in that original is the consumer's and a line absent from it
// (or absent because there was no original at all) is ours.
func (o *ownership) seedGitignore(root string) {
	orig, hasOrig := readOriginal(root, gitignoreTarget)
	for _, want := range gitignoreWants {
		if o.has(kindGitignore, want) {
			continue
		}
		if hasOrig && containsLine(string(orig), want) {
			o.set(kindGitignore, want, originPreexisting)
		} else {
			o.set(kindGitignore, want, originCreated)
		}
	}
}

// loadOwnershipFor returns the ledger, seeding it first when a prior install
// is proven by a non-empty base manifest and no ledger exists yet. A
// first-ever install into a brownfield repository has no manifest, so it
// decides live and records `preexisting` correctly.
func loadOwnershipFor(root string, targets []Target, base map[string][]byte) *ownership {
	o := loadOwnership(root)
	if len(o.origin) == 0 && len(base) > 0 {
		o.seedLegacy(root, targets, base)
	}
	return o
}

// ownedGitignoreLines returns the managed ignore lines the installer is
// recorded as having added. A line the consumer already had is not ours to
// remove (F07); an unrecorded line is unknown, and unknown means keep.
func (o *ownership) ownedGitignoreLines() []string {
	var owned []string
	for _, want := range gitignoreWants {
		if o.get(kindGitignore, want) == originCreated {
			owned = append(owned, want)
		}
	}
	return owned
}
