//! The durable record of who created each managed byte (ADR 0008).
//!
//! Presence on disk is a fact about now; provenance is a fact about the past,
//! and the past is only knowable if it was written down at the time. An origin
//! is therefore fixed on the first decision for a key and never revised — a
//! second install cannot relabel bytes the first one generated, and uninstall
//! never infers ownership from a stat call.

use std::collections::HashMap;
use std::fs;
use std::path::Path;

use super::{
    capture_original, contains_line, gitignore_wants, read_original, sha, write_file_atomic,
    Target, AGENTS_TARGET, GITIGNORE_TARGET,
};

pub const OWNERSHIP_FILE: &str = ".zharness/base/ownership.tsv";

pub const ORIGIN_CREATED: &str = "created_by_installer";
pub const ORIGIN_PREEXISTING: &str = "preexisting";
pub const ORIGIN_UNKNOWN: &str = "unknown";

pub const KIND_FILE: &str = "file";
pub const KIND_GITIGNORE: &str = "gitignore";

#[derive(Debug, Default)]
pub struct Ownership {
    /// `"kind\tkey"`, in stable output order.
    order: Vec<String>,
    origin: HashMap<String, String>,
}

fn own_key(kind: &str, key: &str) -> String {
    format!("{kind}\t{key}")
}

impl Ownership {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn load(root: &Path) -> Self {
        let mut o = Self::new();
        let raw = match fs::read_to_string(root.join(OWNERSHIP_FILE)) {
            Ok(s) => s,
            Err(_) => return o,
        };
        for ln in raw.trim_end_matches('\n').split('\n') {
            let parts: Vec<&str> = ln.split('\t').collect();
            if parts.len() != 3 {
                continue;
            }
            o.set(parts[0], parts[1], parts[2]);
        }
        o
    }

    pub fn set(&mut self, kind: &str, key: &str, origin: &str) {
        let k = own_key(kind, key);
        if !self.origin.contains_key(&k) {
            self.order.push(k.clone());
        }
        self.origin.insert(k, origin.to_string());
    }

    pub fn has(&self, kind: &str, key: &str) -> bool {
        self.origin.contains_key(&own_key(kind, key))
    }

    /// Fixes an origin the first time a key is seen and returns whatever is
    /// already recorded on every later call.
    pub fn record(&mut self, kind: &str, key: &str, origin: &str) -> String {
        let k = own_key(kind, key);
        if let Some(cur) = self.origin.get(&k) {
            return cur.clone();
        }
        self.set(kind, key, origin);
        origin.to_string()
    }

    pub fn get(&self, kind: &str, key: &str) -> String {
        self.origin
            .get(&own_key(kind, key))
            .cloned()
            .unwrap_or_else(|| ORIGIN_UNKNOWN.to_string())
    }

    pub fn save(&self, root: &Path) -> Result<(), String> {
        let mut b = String::new();
        for k in &self.order {
            let parts: Vec<&str> = k.splitn(2, '\t').collect();
            if parts.len() != 2 {
                continue;
            }
            let origin = self.origin.get(k).cloned().unwrap_or_default();
            b.push_str(&format!("{}\t{}\t{origin}\n", parts[0], parts[1]));
        }
        write_file_atomic(&root.join(OWNERSHIP_FILE), b.as_bytes())
    }

    /// Records, once, whether `dst` predates zharness. Existence on disk
    /// decides only the first time; afterwards the ledger answers, which is
    /// what stops a reinstall from capturing generated bytes as a pre-install
    /// original.
    pub fn decide_file_origin(&mut self, root: &Path, dst: &str) -> String {
        let live = if root.join(dst).exists() {
            ORIGIN_PREEXISTING
        } else {
            ORIGIN_CREATED
        };
        self.record(KIND_FILE, dst, live)
    }

    /// Fixes the origin of every managed path before the installer writes its
    /// first byte. Without this the ledger is only saved after the write loop,
    /// so an install that fails midway leaves generated files on disk with
    /// their provenance still unwritten — and the retry, finding no ledger and
    /// no manifest to seed from, reads those files as pre-existing and
    /// captures the generated bytes as their own original.
    pub fn decide_all(&mut self, root: &Path, targets: &[Target]) {
        for t in targets {
            self.decide_file_origin(root, &t.dst);
        }
        self.decide_file_origin(root, AGENTS_TARGET);
        self.decide_file_origin(root, GITIGNORE_TARGET);
        // An ignore line's provenance has to be fixed here for the same reason
        // a file's does: deciding it inside the writer left the lines on disk
        // ahead of the row naming them ours, so an install interrupted in that
        // window came back and read its own lines as the consumer's.
        let existing = fs::read_to_string(root.join(GITIGNORE_TARGET)).unwrap_or_default();
        for want in gitignore_wants() {
            let origin = if contains_line(&existing, want) {
                ORIGIN_PREEXISTING
            } else {
                ORIGIN_CREATED
            };
            self.record(KIND_GITIGNORE, want, origin);
        }
    }

    /// Reconstructs the ledger for an installation made before it existed,
    /// using only the evidence the pre-ledger code itself relied on.
    ///
    /// `base` carries the recorded upstream sha256 per managed path: an
    /// `.orig` whose content hashes to it is the artifact of a generated file
    /// recorded as its own predecessor, not a real pre-install original.
    pub fn seed_legacy(&mut self, root: &Path, targets: &[Target], base: &HashMap<String, String>) {
        for t in targets {
            self.seed_path(
                root,
                &t.dst,
                base.get(&t.dst).map(String::as_str).unwrap_or(""),
            );
        }
        self.seed_path(root, AGENTS_TARGET, "");
        self.seed_gitignore(root);
    }

    fn seed_path(&mut self, root: &Path, dst: &str, upstream: &str) {
        if self.has(KIND_FILE, dst) {
            return;
        }
        if !root.join(dst).exists() {
            return; // not on disk: let the next install decide live
        }
        match read_original(root, dst) {
            None => self.set(KIND_FILE, dst, ORIGIN_CREATED),
            Some(orig) if !upstream.is_empty() && sha(&orig) == upstream => {
                self.set(KIND_FILE, dst, ORIGIN_CREATED)
            }
            Some(_) => self.set(KIND_FILE, dst, ORIGIN_PREEXISTING),
        }
    }

    /// Exact rather than heuristic: install captured `.gitignore`'s pristine
    /// bytes if and only if the file existed beforehand, so a managed line
    /// present in that original is the consumer's and a line absent from it
    /// (or absent because there was no original at all) is ours.
    fn seed_gitignore(&mut self, root: &Path) {
        let orig = read_original(root, GITIGNORE_TARGET);
        for want in gitignore_wants() {
            if self.has(KIND_GITIGNORE, want) {
                continue;
            }
            let origin = match &orig {
                Some(o) if contains_line(&String::from_utf8_lossy(o), want) => ORIGIN_PREEXISTING,
                _ => ORIGIN_CREATED,
            };
            self.set(KIND_GITIGNORE, want, origin);
        }
    }

    /// The managed ignore lines the installer is recorded as having added. A
    /// line the consumer already had is not ours to remove; an unrecorded line
    /// is unknown, and unknown means keep.
    pub fn owned_gitignore_lines(&self) -> Vec<String> {
        gitignore_wants()
            .iter()
            .filter(|w| self.get(KIND_GITIGNORE, w) == ORIGIN_CREATED)
            .map(|w| w.to_string())
            .collect()
    }
}

/// The ledger, seeded first when a prior install is proven by a non-empty base
/// manifest and no ledger exists yet. A first-ever install into a brownfield
/// repository has no manifest, so it decides live and records `preexisting`
/// correctly.
pub fn load_ownership_for(
    root: &Path,
    targets: &[Target],
    base: &HashMap<String, String>,
) -> Ownership {
    let mut o = Ownership::load(root);
    if o.order.is_empty() && !base.is_empty() {
        o.seed_legacy(root, targets, base);
    }
    o
}

/// Captures a pristine copy only for a path the ledger attributes to the
/// consumer.
pub fn capture_if_preexisting(root: &Path, o: &mut Ownership, dst: &str) -> Result<(), String> {
    if o.decide_file_origin(root, dst) != ORIGIN_PREEXISTING {
        return Ok(());
    }
    capture_original(root, dst)
}
